### ISSUE TITLE
Okta Verify with Push does not show up in factor reset UI

### ISSUE THREAD

**Issue by Manjunath-hk1** [lithnet/resourcemanagement-ui-oktafactormanagement#1]
The factor reset UI doesn't show up with the "OKTA/token:software:totp" set for the user.

**Comment by ryannewington** [comment]
Can you elaborate? Screen shot?

**Comment by Manjunath-hk1** [comment]
I tried to reproduce steps to reset and register my account and that was working as expected.I will try to reproduce by resetting factors randomly.
The user scenario was like user was trying to setup factors in other phone and it was error.we could not see any factor set in FIM portal but can see the factors set in Okta portal "Okta Verify with Push".By factor reset in okta it worked for user.
I am exploring options to reproduce.
